baseURL = "https://hakomori64.github.io/"
languageCode = "ja-jp"
title = "Yu's Blog"
theme = "ananke"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"

[menu]

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
